import { NextResponse } from 'next/server';
import { getMidtransConfig } from '../../../../lib/midtrans/config';
import { verifyMidtransSignature } from '../../../../lib/midtrans/verify-notification';
import { getSupabaseServerClient } from '../../../../lib/supabase/server';
import { getMidtransTransactionStatus } from '../../../../lib/midtrans/client';
import { applyVerifiedStatus } from '../../../../lib/midtrans/orders';
import { serverLog } from '../../../../lib/orders/logger';
import type { MidtransStatusResponse } from '../../../../lib/midtrans/types';
export async function POST(request: Request) { try { const cfg=getMidtransConfig(); if(!cfg.serverKey) return NextResponse.json({ok:false},{status:503}); const payload=await request.json() as MidtransStatusResponse; serverLog('info','payment.webhook.received',{providerOrderId:payload.order_id}); if(!verifyMidtransSignature(payload,cfg.serverKey)) { serverLog('warn','payment.webhook.invalid_signature',{providerOrderId:payload.order_id}); return NextResponse.json({ok:false},{status:401}); } const s=getSupabaseServerClient(); if(!s || !payload.order_id) return NextResponse.json({ok:false},{status:503}); const {data:attempt}=await s.from('payment_attempts').select('*').eq('provider_order_id',payload.order_id).single(); if(!attempt) { serverLog('warn','payment.webhook.unknown_attempt',{providerOrderId:payload.order_id}); return NextResponse.json({ok:true}); } const {data:order}=await s.from('orders').select('*').eq('id',attempt.order_id).single(); if(!order) return NextResponse.json({ok:true}); let verified=payload; try { verified=await getMidtransTransactionStatus(payload.order_id); } catch(e) { serverLog('warn','payment.get_status.failed',{providerOrderId:payload.order_id,message:e instanceof Error?e.message:'Unknown'}); } await applyVerifiedStatus(order,attempt,verified); return NextResponse.json({ok:true}); } catch(e) { serverLog('error','payment.webhook.failed',{message:e instanceof Error?e.message:'Unknown'}); return NextResponse.json({ok:false},{status:400}); } }
