import 'server-only';
import { getRuntimeMode, getSupabaseServerClient } from '../supabase/server';
import { products, type Product } from '../products';
import { isProductPurchasable, mapProductDbError, productWriteSchema } from './validation';
import { derivePublicCategories, parseCategoryQuery, normalizeCategoryValue } from './categories';

type ProductRow = { id:string; slug:string; sku:string; name:string; short_description:string; description:string; price:number; compare_at_price:number|null; currency:'IDR'; weight_grams:number; protein_grams:number|null; serving_size_grams:number|null; ingredients:string|null; allergen_information:string|null; category:string|null; image_url:string|null; image_alt:string|null; additional_images:string[]|null; is_active:boolean; is_available:boolean; is_featured:boolean; is_best_seller?:boolean; display_order:number; created_at:string; updated_at:string };
export type ProductInput = ReturnType<typeof productWriteSchema.parse>;
export type AdminProductListParams = { q?: string; status?: string; page?: string; pageSize?: string };
function toProduct(r: ProductRow): Product { return { id:r.id, slug:r.slug, sku:r.sku, name:r.name, shortDescription:r.short_description, description:r.description, price:r.price, compareAtPrice:r.compare_at_price, currency:r.currency, weight:`${r.weight_grams} g`, weightGrams:r.weight_grams, protein:r.protein_grams == null ? '-' : `${r.protein_grams} g`, proteinGrams:r.protein_grams, servingSizeGrams:r.serving_size_grams, ingredients:r.ingredients, allergenInformation:r.allergen_information, category:r.category, imageUrl:r.image_url, imageAlt:r.image_alt ?? r.name, additionalImages:r.additional_images ?? [], status:r.is_active?'active':'inactive', isActive:r.is_active, isAvailable:r.is_available, isFeatured:r.is_featured, isBestSeller:r.is_best_seller ?? false, displayOrder:r.display_order, badge:r.is_featured?'Produk Unggulan':(r.is_available?'Tersedia':'Tidak Tersedia'), accent:'#d8ae57', createdAt:r.created_at, updatedAt:r.updated_at }; }
function toDb(input: ProductInput) { return { name: input.name, slug: input.slug, sku: input.sku, category: input.category ?? null, short_description: input.shortDescription, description: input.description, price: input.price, compare_at_price: input.compareAtPrice ?? null, currency: 'IDR', weight_grams: input.weightGrams, protein_grams: input.proteinGrams ?? null, serving_size_grams: input.servingSizeGrams ?? null, ingredients: input.ingredients ?? null, allergen_information: input.allergenInformation ?? null, image_url: input.imageUrl ?? null, image_alt: input.imageAlt || input.name, additional_images: input.additionalImages ?? [], is_active: input.isActive, is_available: input.isActive ? input.isAvailable : false, is_featured: input.isFeatured, is_best_seller: input.isBestSeller, display_order: input.displayOrder }; }
const columns = 'id,slug,sku,name,short_description,description,price,compare_at_price,currency,weight_grams,protein_grams,serving_size_grams,ingredients,allergen_information,category,image_url,image_alt,additional_images,is_active,is_available,is_featured,is_best_seller,display_order,created_at,updated_at';
export async function listPublicProducts(): Promise<Product[]> { const s=getSupabaseServerClient(); if(!s) return sortProducts(products.filter(p=>p.isActive)); const {data,error}=await s.from('products').select(columns).eq('is_active',true).order('display_order').order('name'); if(error) throw new Error('Failed to load products'); return (data as ProductRow[]).map(toProduct); }
function sortProducts(rows: Product[]) { return [...rows].sort((a,b)=>a.displayOrder-b.displayOrder||a.name.localeCompare(b.name)); }
export type PublicMerchandisingCatalog = { products: Product[]; featuredProducts: Product[]; bestSellerProducts: Product[]; categories: ReturnType<typeof derivePublicCategories>; selectedCategory: ReturnType<typeof derivePublicCategories>[number] | null; selectedCategoryValue: string | null; filteredProducts: Product[]; hasInvalidCategory: boolean };
export function buildPublicMerchandisingCatalog(allProducts: Product[], categoryQuery?: string | string[] | null): PublicMerchandisingCatalog { const all=sortProducts(allProducts.filter(p=>p.isActive)); const categories=derivePublicCategories(all); const selectedValue=parseCategoryQuery(categoryQuery); const selectedCategory=categories.find(c=>c.value===selectedValue)??null; const filterValue=selectedCategory?.value??selectedValue; const filteredProducts=filterValue?all.filter(p=>normalizeCategoryValue(p.category)===filterValue):all; return { products: all, featuredProducts: all.filter(p=>p.isFeatured).slice(0,4), bestSellerProducts: all.filter(p=>p.isBestSeller).slice(0,4), categories, selectedCategory, selectedCategoryValue: filterValue, filteredProducts, hasInvalidCategory: Boolean(selectedValue && !selectedCategory) }; }
export async function getPublicMerchandisingCatalog(categoryQuery?: string | string[] | null): Promise<PublicMerchandisingCatalog> { return buildPublicMerchandisingCatalog(await listPublicProducts(), categoryQuery); }
export async function getTrustedProductsByIds(ids:string[]) { const unique=[...new Set(ids)].filter(Boolean); const s=getSupabaseServerClient(); const rows = s ? ((await s.from('products').select(columns).in('id', unique)).data as ProductRow[]|null)?.map(toProduct) ?? [] : products.filter(p=>unique.includes(p.id)); return new Map(rows.map(p=>[p.id,p])); }
export async function listAdminProducts(params: AdminProductListParams) { if(getRuntimeMode()==='demo') return { rows: products, total: products.length, page:1, pageSize:20, hasPrev:false, hasNext:false, mode:'demo' as const }; const s=getSupabaseServerClient(); if(!s) throw new Error('Database unavailable'); const page=Math.max(1, Number(params.page)||1), pageSize=Math.min(50, Math.max(1, Number(params.pageSize)||20)); let q=s.from('products').select(columns,{count:'exact'}); const term=(params.q??'').trim().slice(0,100); if(term) q=q.or(`name.ilike.%${term.replace(/[%_,]/g,'')}%,sku.ilike.%${term.replace(/[%_,]/g,'')}%,slug.ilike.%${term.replace(/[%_,]/g,'')}%,category.ilike.%${term.replace(/[%_,]/g,'')}%`); if(params.status==='active') q=q.eq('is_active',true); if(params.status==='inactive') q=q.eq('is_active',false); if(params.status==='available') q=q.eq('is_available',true); if(params.status==='unavailable') q=q.eq('is_available',false); if(params.status==='featured') q=q.eq('is_featured',true); if(params.status==='best-seller') q=q.eq('is_best_seller',true); const {data,error,count}=await q.order('display_order').order('name').range((page-1)*pageSize,page*pageSize-1); if(error) throw new Error('Failed to load admin products'); const total=count??0; return { rows:(data as ProductRow[]).map(toProduct), total, page, pageSize, hasPrev:page>1, hasNext:page*pageSize<total, mode:'supabase' as const }; }
export async function getAdminProduct(id:string){ const s=getSupabaseServerClient(); if(!s) return products.find(p=>p.id===id)??null; const {data}=await s.from('products').select(columns).eq('id',id).maybeSingle(); return data?toProduct(data as ProductRow):null; }
export async function createProduct(raw: unknown){ if(getRuntimeMode()==='demo') throw new Error('Pengelolaan produk membutuhkan konfigurasi database Supabase.'); const input=productWriteSchema.parse(raw); const s=getSupabaseServerClient(); if(!s) throw new Error('Database unavailable'); const {data,error}=await s.from('products').insert(toDb(input)).select(columns).single(); if(error) throw new Error(mapProductDbError(error)); console.info('product.created',{productId:data.id,sku:data.sku}); return toProduct(data as ProductRow); }
export async function updateProduct(id:string, raw: unknown){ if(getRuntimeMode()==='demo') throw new Error('Pengelolaan produk membutuhkan konfigurasi database Supabase.'); const input=productWriteSchema.parse(raw); const s=getSupabaseServerClient(); if(!s) throw new Error('Database unavailable'); const existing=await getAdminProduct(id); if(!existing) return null; if(input.updatedAt && existing.updatedAt && input.updatedAt!==existing.updatedAt){ console.warn('product.update.conflict',{productId:id,sku:existing.sku}); const e=new Error('Produk telah diperbarui dari sesi lain. Muat ulang halaman sebelum menyimpan perubahan.'); (e as Error & {status?:number}).status=409; throw e; } const {data,error}=await s.from('products').update(toDb(input)).eq('id',id).select(columns).single(); if(error) throw new Error(mapProductDbError(error)); console.info('product.updated',{productId:id,sku:data.sku}); return toProduct(data as ProductRow); }
export async function updateProductStatus(id:string, patch:{isActive?:boolean;isAvailable?:boolean;isFeatured?:boolean}){ if(getRuntimeMode()==='demo') throw new Error('Pengelolaan produk membutuhkan konfigurasi database Supabase.'); const s=getSupabaseServerClient(); if(!s) throw new Error('Database unavailable'); const db:Record<string,boolean>={}; if(typeof patch.isActive==='boolean') db.is_active=patch.isActive; if(typeof patch.isAvailable==='boolean') db.is_available=patch.isAvailable; if(typeof patch.isFeatured==='boolean') db.is_featured=patch.isFeatured; if(db.is_active===false) db.is_available=false; const {data,error}=await s.from('products').update(db).eq('id',id).select(columns).single(); if(error) throw new Error('Status produk belum dapat diperbarui.'); console.info('product.status.updated',{productId:id}); return toProduct(data as ProductRow); }
export { isProductPurchasable };

export async function listActiveAdminProductsForDestinations() {
  const result = await listAdminProducts({ status: 'active', pageSize: '50' });
  return result.rows.filter(product => product.isActive).map(product => ({ id: product.id, slug: product.slug, name: product.name, category: product.category, isActive: product.isActive }));
}
