import { z } from 'zod';
export function normalizeSlug(value: string) { return value.normalize('NFKD').toLowerCase().replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/-{2,}/g, '-').replace(/^-|-$/g, ''); }
export function normalizeSku(value: string) { return value.trim().toUpperCase().replace(/\s+/g, '-').replace(/[^A-Z0-9._-]/g, ''); }
const optionalText = (max: number) => z.preprocess(v => (typeof v === 'string' && v.trim() === '' ? null : v), z.string().trim().max(max).nullable().optional());
const intField = z.coerce.number().int();
export const productWriteSchema = z.object({ name: z.string().trim().min(2).max(150), slug: z.string().trim().min(2).max(160).transform(normalizeSlug), sku: z.string().trim().min(2).max(80).transform(normalizeSku), category: optionalText(100), shortDescription: z.string().trim().min(2).max(300), description: z.string().trim().min(2).max(10000), price: intField.positive(), compareAtPrice: z.preprocess(v => v === '' || v == null ? null : v, intField.positive().nullable()).optional(), weightGrams: intField.positive().max(100000), proteinGrams: z.preprocess(v => v === '' || v == null ? null : v, z.coerce.number().min(0).max(10000).nullable()).optional(), servingSizeGrams: z.preprocess(v => v === '' || v == null ? null : v, z.coerce.number().positive().max(100000).nullable()).optional(), ingredients: optionalText(5000), allergenInformation: optionalText(2000), imageUrl: optionalText(2000), imageAlt: z.string().trim().max(200).optional().default(''), additionalImages: z.array(z.string().trim().max(2000)).max(8).optional().default([]), isActive: z.coerce.boolean().default(false), isAvailable: z.coerce.boolean().default(false), isFeatured: z.coerce.boolean().default(false), isBestSeller: z.coerce.boolean().default(false), displayOrder: intField.min(-100000).max(100000).default(100), updatedAt: z.string().optional() }).superRefine((v, ctx) => { if (v.compareAtPrice != null && v.compareAtPrice <= v.price) ctx.addIssue({ code: 'custom', path: ['compareAtPrice'], message: 'Harga pembanding harus lebih besar dari harga.' }); if (v.isActive && v.imageUrl && !v.imageAlt.trim()) ctx.addIssue({ code: 'custom', path: ['imageAlt'], message: 'Alt text gambar wajib diisi untuk produk aktif.' }); });
export const productStatusSchema = z.object({ isActive: z.boolean().optional(), isAvailable: z.boolean().optional(), isFeatured: z.boolean().optional() }).refine(v => Object.keys(v).length > 0);
export function isProductPurchasable(p: { isActive: boolean; isAvailable: boolean; price: number }) { return p.isActive === true && p.isAvailable === true && p.price > 0; }
export function mapProductDbError(error: unknown) { const msg = error && typeof error === 'object' && 'message' in error ? String((error as {message?:unknown}).message) : ''; if (/slug/i.test(msg)) return 'Slug produk sudah digunakan.'; if (/sku/i.test(msg)) return 'SKU produk sudah digunakan.'; return 'Produk belum dapat disimpan.'; }
