import 'server-only';
import { getSupabaseServerClient } from '../supabase/server';
import { serverLog } from '../orders/logger';
import { getMidtransConfig } from './config';
import { amountsMatch } from './verify-notification';
import { canRetryPayment, canTransitionPaymentStatus, generateProviderOrderId, isPaymentStatus, mapMidtransStatus } from './status';
import type { MidtransStatusResponse, PaymentStatus, SnapTransactionRequest } from './types';
import type { PersistedOrder } from '../orders/types';
import { createOrderEvent } from '../orders/events';

const PAYMENT_EVENT_TITLES: Record<PaymentStatus, string> = { unpaid: 'Belum Dibayar', pending: 'Menunggu Pembayaran', paid: 'Pembayaran Diterima', failed: 'Pembayaran Gagal', expired: 'Pembayaran Kedaluwarsa', cancelled: 'Pembayaran Dibatalkan', challenged: 'Pembayaran Ditinjau', refunded: 'Dana Dikembalikan' };
export function buildSnapPayload(order: PersistedOrder, providerOrderId: string): SnapTransactionRequest { const item_details = order.items.map(i=>({ id:i.productId.slice(0,50), name:i.productName.slice(0,50), price:i.unitPrice, quantity:i.quantity })); const sum = item_details.reduce((s,i)=>s+i.price*i.quantity,0); if (sum !== order.grandTotal) item_details.push({ id:'ADJUSTMENT', name:'Penyesuaian total', price: order.grandTotal-sum, quantity:1 }); return { transaction_details:{ order_id:providerOrderId, gross_amount:order.grandTotal }, item_details, customer_details:{ first_name:order.customerName.slice(0,50), email:order.email || undefined, phone:order.whatsapp, billing_address:{ address:[order.address,order.district,order.province].join(', ').slice(0,200), city:order.city, postal_code:order.postalCode, country_code:'IDN' }, shipping_address:{ address:[order.address,order.district,order.province].join(', ').slice(0,200), city:order.city, postal_code:order.postalCode, country_code:'IDN' } }, callbacks: getMidtransConfig().appUrl ? { finish: `${getMidtransConfig().appUrl}/orders/${order.orderNumber}` } : undefined }; }
export function isOrderEligibleForPayment(order: PersistedOrder) { if (!order.items.length || order.grandTotal <= 0) return false; if (['completed','cancelled'].includes(order.status)) return false; return order.paymentStatus !== 'paid'; }
export async function getLatestPaymentAttempt(orderId: string) { const s=getSupabaseServerClient(); if(!s) return null; const {data}=await s.from('payment_attempts').select('*').eq('order_id',orderId).order('created_at',{ascending:false}).limit(1).maybeSingle(); return data as any | null; }
export async function createPaymentAttempt(order: PersistedOrder, token: string, redirectUrl: string) { const s=getSupabaseServerClient(); if(!s || !order.id) throw new Error('Database unavailable'); const attemptNo=(order.paymentAttemptCount ?? 0)+1; const providerOrderId=generateProviderOrderId(order.orderNumber,attemptNo); const {data,error}=await s.from('payment_attempts').insert({ order_id:order.id, provider:'midtrans', provider_order_id:providerOrderId, snap_token:token, redirect_url:redirectUrl, gross_amount:order.grandTotal }).select('*').single(); if(error) throw new Error('Failed to save payment attempt'); await s.from('orders').update({ payment_provider:'midtrans', payment_status:'pending', midtrans_snap_token:token, midtrans_redirect_url:redirectUrl, payment_attempt_count:attemptNo, payment_updated_at:new Date().toISOString() }).eq('id',order.id); await createOrderEvent({ orderId: order.id, eventType: 'payment_attempt_created', orderStatus: order.status, paymentStatus: 'pending', title: 'Percobaan Pembayaran Dibuat', description: 'Link pembayaran online dibuat.', source: 'system' }); serverLog('info','payment.attempt.created',{orderNumber:order.orderNumber,providerOrderId}); return data as any; }
export async function applyVerifiedStatus(order:any, attempt:any, status: MidtransStatusResponse) { const s=getSupabaseServerClient(); if(!s) throw new Error('Database unavailable'); if(!amountsMatch(status.gross_amount, Number(attempt.gross_amount))) { serverLog('warn','payment.amount_mismatch',{orderNumber:order.order_number,providerOrderId:attempt.provider_order_id}); throw new Error('Amount mismatch'); } const current: PaymentStatus = isPaymentStatus(order.payment_status) ? order.payment_status : 'unpaid'; const next = mapMidtransStatus(status.transaction_status, status.fraud_status); const updates:any = { payment_type: status.payment_type ?? order.payment_type, midtrans_transaction_id: status.transaction_id ?? order.midtrans_transaction_id, midtrans_transaction_status: status.transaction_status, midtrans_fraud_status: status.fraud_status ?? null, midtrans_status_code: status.status_code ?? null, midtrans_status_message: status.status_message ?? null, midtrans_transaction_time: status.transaction_time ?? null, midtrans_settlement_time: status.settlement_time ?? null, midtrans_expiry_time: status.expiry_time ?? null, payment_updated_at: new Date().toISOString() };
 if (canTransitionPaymentStatus(current,next)) { updates.payment_status=next; if(next==='paid' && !order.paid_at) updates.paid_at=new Date().toISOString(); if(next==='paid' && order.status==='pending') updates.status='confirmed'; serverLog('info','payment.status.transition',{orderNumber:order.order_number,from:current,to:next,providerOrderId:attempt.provider_order_id}); }
 await s.from('orders').update(updates).eq('id',order.id); if (updates.payment_status) await createOrderEvent({ orderId: order.id, eventType: `payment_${updates.payment_status}`, orderStatus: updates.status ?? order.status, paymentStatus: updates.payment_status, title: PAYMENT_EVENT_TITLES[updates.payment_status as PaymentStatus] ?? 'Status Pembayaran Diperbarui', description: 'Status pembayaran diperbarui dari verifikasi Midtrans.', source: 'midtrans' }); await s.from('payment_attempts').update({ transaction_id: status.transaction_id ?? attempt.transaction_id, transaction_status: status.transaction_status, fraud_status: status.fraud_status ?? null, payment_type: status.payment_type ?? null, raw_status: status, updated_at:new Date().toISOString() }).eq('id',attempt.id); return { paymentStatus: updates.payment_status ?? current, changed: Boolean(updates.payment_status) };
}
export { canRetryPayment, generateProviderOrderId };
