import Link from 'next/link';
import { findOrder, getOrderAccessTokenHash } from '../../../lib/orders/repository';
import { verifyOrderAccessToken } from '../../../lib/orders/access';
import { formatRupiah } from '../../../lib/format';
import { PAYMENT_STATUS_LABELS, canRetryPayment } from '../../../lib/midtrans/status';
import { ORDER_STATUS_LABELS } from '../../../lib/admin/status';
import { MidtransPayButton } from '../../../components/payment/MidtransSnap';
function date(v?:string|null){ return v ? new Intl.DateTimeFormat('id-ID',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v)) : '-'; }
export default async function OrderStatusPage({params,searchParams}:{params:Promise<{orderNumber:string}>;searchParams:Promise<{accessToken?:string}>}){ const {orderNumber}=await params; const sp=await searchParams; const {order}=await findOrder(orderNumber); if(!order) return <main className="safe mx-auto grid min-h-screen max-w-md place-items-center px-4"><section className="rounded-3xl bg-white p-6 text-center shadow-card"><h1 className="text-2xl font-black">Pesanan tidak ditemukan</h1><Link className="mt-5 inline-flex rounded-full bg-soia-green px-5 py-3 font-bold text-white" href="/">Kembali Belanja</Link></section></main>; const tokenHash=await getOrderAccessTokenHash(orderNumber); if(tokenHash && !verifyOrderAccessToken(sp.accessToken ?? '', tokenHash)) return <main className="safe mx-auto grid min-h-screen max-w-md place-items-center px-4"><section className="rounded-3xl bg-white p-6 text-center shadow-card"><h1 className="text-2xl font-black">Akses pesanan tidak valid</h1><p className="mt-2 text-sm text-soia-green/60">Buka tautan pesanan lengkap dari halaman checkout.</p><Link className="mt-5 inline-flex rounded-full bg-soia-green px-5 py-3 font-bold text-white" href="/">Kembali Belanja</Link></section></main>; const label=PAYMENT_STATUS_LABELS[order.paymentStatus]; return <main className="safe mx-auto min-h-screen max-w-2xl px-4 pb-24 text-soia-green"><section className="mt-6 rounded-[2rem] bg-white p-6 shadow-card"><p className="text-xs font-black uppercase tracking-[0.16em] text-soia-green/45">Status Pesanan</p><h1 className="mt-2 break-all text-3xl font-black">{order.orderNumber}</h1><div className="mt-5 grid gap-3 sm:grid-cols-2"><Info label="Tanggal" value={date(order.createdAt)}/><Info label="Total" value={formatRupiah(order.grandTotal)}/><Info label="Status Order" value={ORDER_STATUS_LABELS[order.status]}/><Info label="Status Pembayaran" value={label}/><Info label="Metode" value={order.paymentType ?? '-'}/><Info label="Kedaluwarsa" value={date(order.midtransExpiryTime)}/><Info label="Dibayar" value={date(order.paidAt)}/></div><div className="mt-6 grid gap-3 sm:grid-cols-2">{canRetryPayment(order.paymentStatus)?<MidtransPayButton orderNumber={order.orderNumber} accessToken={sp.accessToken}>{order.paymentStatus==='unpaid'?'Bayar Sekarang':'Coba Lagi'}</MidtransPayButton>:null}<Link className="flex min-h-12 items-center justify-center rounded-full border font-bold" href="/">Kembali Belanja</Link></div></section></main>; }
function Info({label,value}:{label:string;value:string}){return <div className="rounded-2xl bg-soia-cream/70 p-4"><p className="text-xs font-black uppercase text-soia-green/45">{label}</p><strong className="mt-1 block">{value}</strong></div>}
