import Link from 'next/link';
import { requireAdminSession } from '../../../../lib/admin/auth';
import { formatAdminDate } from '../../../../lib/admin/format';
import { getRuntimeMode } from '../../../../lib/supabase/server';
import { listAdminBanners } from '../../../../lib/merchandising/repository';
import { getBannerScheduleState } from '../../../../lib/merchandising/schedule';
const stateLabels={active:'Sedang Tayang',scheduled:'Terjadwal',expired:'Berakhir',inactive:'Tidak Aktif'};
function destination(row:{destination_type:string;destination_value:string|null}){ if(row.destination_type==='none') return 'Tanpa tujuan'; if(row.destination_type==='featured') return 'Produk Unggulan'; if(row.destination_type==='all_products') return 'Semua Produk'; return `${row.destination_type}: ${row.destination_value??'-'}`; }
export default async function BannerListPage(){ await requireAdminSession(); const result=await listAdminBanners(); return <section><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-3xl font-black">Banner Storefront</h1><p className="font-semibold text-soia-green/60">{result.rows.length} banner</p></div><Link href="/admin/storefront/banners/new" className="rounded-full bg-soia-green px-5 py-3 font-bold text-white">Buat Banner</Link></div>{result.mode==='demo'||getRuntimeMode()==='demo'?<p className="mt-4 rounded-2xl bg-amber-50 p-4 font-bold text-amber-800">Pengelolaan banner membutuhkan konfigurasi database dan storage Supabase.</p>:null}{result.rows.length===0?<div className="mt-6 rounded-3xl bg-white p-8 text-center shadow-card"><p className="font-black">Belum ada banner storefront.</p><Link href="/admin/storefront/banners/new" className="mt-4 inline-flex rounded-full bg-soia-green px-5 py-3 font-bold text-white">Buat Banner Pertama</Link></div>:<><div className="mt-6 hidden overflow-hidden rounded-3xl bg-white shadow-card md:block"><table className="w-full text-left text-sm"><thead className="bg-soia-green/5"><tr>{['Gambar','Judul','Tujuan','Status Publikasi','Status Jadwal','Urutan','Diperbarui','Aksi'].map(h=><th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{result.rows.map(row=><tr key={row.id} className="border-t"><td className="p-3"><img src={row.image_url} alt={row.image_alt} loading="lazy" className="h-12 w-24 rounded-xl bg-soia-green/10 object-cover"/></td><td className="p-3 font-bold">{row.title||'(Tanpa judul)'}</td><td className="p-3">{destination(row)}</td><td className="p-3">{row.is_active?'Aktif':'Tidak Aktif'}</td><td className="p-3">{stateLabels[getBannerScheduleState(row)]}</td><td className="p-3">{row.display_order}</td><td className="p-3">{formatAdminDate(row.updated_at)}</td><td className="p-3"><div className="flex flex-wrap gap-2"><Link className="font-bold underline" href={`/admin/storefront/banners/${row.id}`}>Edit</Link><form action={`/api/admin/storefront/banners/${row.id}/status`} method="post"><input type="hidden" name="active" value={row.is_active?'false':'true'}/><button className="font-bold underline">{row.is_active?'Nonaktifkan':'Aktifkan'}</button></form><Link className="font-bold text-red-700 underline" href={`/admin/storefront/banners/${row.id}`}>Hapus</Link></div></td></tr>)}</tbody></table></div><div className="mt-6 grid gap-3 md:hidden">{result.rows.map(row=><article key={row.id} className="rounded-3xl bg-white p-4 shadow-card"><p className="break-words font-black">{row.title||'(Tanpa judul)'}</p><p>{row.is_active?'Aktif':'Tidak Aktif'} · {stateLabels[getBannerScheduleState(row)]}</p><p className="text-sm">{destination(row)} · Urutan {row.display_order}</p><Link className="mt-3 inline-flex min-h-11 items-center font-bold underline" href={`/admin/storefront/banners/${row.id}`}>Lihat / Edit</Link></article>)}</div></>}</section> }
