import assert from 'node:assert/strict';
import test from 'node:test';
const allowed = new Map([['image/jpeg','jpg'],['image/png','png'],['image/webp','webp']]);
const max = 5 * 1024 * 1024;
const sanitize = (name, ext='jpg') => name.toLowerCase().replace(/[^a-z0-9._-]+/g, '-').replace(/^-+|-+$/g, '').slice(0,80) || `image.${ext}`;
const validFile = file => !allowed.has(file.type) ? 'type' : file.size <= 0 ? 'empty' : file.size > max ? 'size' : 'ok';
const managed = value => Boolean(value && !/^https?:\/\//i.test(value) && /^banners\/[a-zA-Z0-9._-]{2,120}\/[a-zA-Z0-9._-]+$/.test(value));
const safePath = value => value.startsWith('/') && !value.startsWith('//') && !/^\/(admin|api)(\/|$)/i.test(value) && !/https?:|javascript:|data:|:\/\//i.test(value);
const allowlisted = raw => ({ title:raw.title??null, subtitle:raw.subtitle??null, eyebrow_text:raw.eyebrowText??null, image_url:raw.imageUrl, mobile_image_url:raw.mobileImageUrl??null, image_alt:raw.imageAlt, cta_label:raw.ctaLabel??null, destination_type:raw.destinationType, destination_value:raw.destinationValue??null, is_active:raw.isActive, display_order:raw.displayOrder, text_theme:raw.textTheme, overlay_strength:raw.overlayStrength, background_color:raw.backgroundColor??null, starts_at:raw.startsAt??null, ends_at:raw.endsAt??null });
const activeProducts = [{id:'soia-original',slug:'soia-original',category:'Snack Protein',isActive:true},{id:'inactive',slug:'inactive',category:'Old',isActive:false}];
const categorySlug = value => value.toLowerCase().replace(/\s+/g,'-').replace(/[^a-z0-9-]/g,'').replace(/-{2,}/g,'-').replace(/^-|-$/g,'');
function productDestinationExists(value){ return activeProducts.filter(p=>p.isActive).some(p=>p.id===value||p.slug===value); }
function categoryDestinationExists(value){ return activeProducts.filter(p=>p.isActive).some(p=>categorySlug(p.category)===value); }
function canActivate(row){ return Boolean(row.image_url && row.image_alt?.trim() && (!row.starts_at || !row.ends_at || Date.parse(row.ends_at)>Date.parse(row.starts_at))); }

test('admin banner image validation rejects invalid type, empty, and oversized files', () => { assert.equal(validFile({type:'image/gif',size:10}), 'type'); assert.equal(validFile({type:'image/png',size:0}), 'empty'); assert.equal(validFile({type:'image/webp',size:max+1}), 'size'); assert.equal(validFile({type:'image/jpeg',size:max}), 'ok'); });
test('filename sanitization removes unsafe characters and keeps a fallback', () => { assert.equal(sanitize('Promo Juli!!.PNG'), 'promo-juli-.png'); assert.equal(sanitize('????','png'), 'image.png'); });
test('managed banner path detection refuses unrelated storage and external URLs', () => { assert.equal(managed('banners/tmp-123/123-file.webp'), true); assert.equal(managed('products/uploads/file.webp'), false); assert.equal(managed('https://cdn.example.com/banners/tmp/file.webp'), false); assert.equal(managed('../banners/tmp/file.webp'), false); });
test('mutation mapping prevents mass assignment', () => { const db=allowlisted({title:'T',imageUrl:'banners/t/a.jpg',imageAlt:'Alt',destinationType:'none',isActive:false,displayOrder:1,textTheme:'light',overlayStrength:0.2,id:'evil',created_at:'evil',admin_identity:'evil'}); assert.equal('id' in db, false); assert.equal('created_at' in db, false); assert.equal('admin_identity' in db, false); assert.equal(db.title, 'T'); });
test('destination validation rejects external URLs and unsafe internal paths', () => { assert.equal(safePath('/products?featured=1'), true); assert.equal(safePath('https://example.com'), false); assert.equal(safePath('/admin'), false); assert.equal(safePath('/api/orders'), false); assert.equal(safePath('//evil.test'), false); });
test('product and category destinations require active canonical products', () => { assert.equal(productDestinationExists('soia-original'), true); assert.equal(productDestinationExists('inactive'), false); assert.equal(categoryDestinationExists('snack-protein'), true); assert.equal(categoryDestinationExists('old'), false); });
test('activation requires complete image and valid schedule', () => { assert.equal(canActivate({image_url:'banners/tmp/a.jpg',image_alt:'Alt',starts_at:null,ends_at:null}), true); assert.equal(canActivate({image_url:'',image_alt:'Alt'}), false); assert.equal(canActivate({image_url:'banners/tmp/a.jpg',image_alt:' '}), false); assert.equal(canActivate({image_url:'banners/tmp/a.jpg',image_alt:'Alt',starts_at:'2026-07-22T00:00:00.000Z',ends_at:'2026-07-21T00:00:00.000Z'}), false); });
test('demo mode write rejection uses safe Indonesian message', () => { const message='Pengelolaan banner membutuhkan konfigurasi database dan storage Supabase.'; assert.match(message, /Supabase/); assert.equal(message.includes('success'), false); });
