import assert from 'node:assert/strict';
import { test } from 'node:test';

const max = 100;
function label(value){ if(typeof value!=='string') return null; const v=value.trim().replace(/\s+/g,' '); if(!v||/[\u0000-\u001f\u007f]/.test(v)) return null; return v.slice(0,max); }
function value(v){ const l=label(v); if(!l) return null; const n=l.normalize('NFKD').toLowerCase().replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/-{2,}/g,'-').replace(/^-|-$/g,''); return n && n.length<=max ? n : null; }
function parse(v){ return typeof v==='string' && v.length<=max && !/[\u0000-\u001f\u007f]/.test(v) ? value(v) : null; }
function cats(products){ const m=new Map(); for(const p of products){ const l=label(p.category), v=value(p.category); if(l&&v){ const existing=m.get(v); if(!existing || (existing===existing.toLowerCase() && l!==l.toLowerCase())) m.set(v,l); } } return [...m].map(([value,label])=>({value,label})).sort((a,b)=>a.label.localeCompare(b.label,'id',{sensitivity:'base'})||a.value.localeCompare(b.value)); }
function href(v){ return v ? `/?category=${encodeURIComponent(v)}#products` : '/#products'; }
function catalog(products, q){ const all=products.filter(p=>p.isActive).sort((a,b)=>a.displayOrder-b.displayOrder||a.name.localeCompare(b.name)); const categories=cats(all); const selectedValue=parse(q); const selectedCategory=categories.find(c=>c.value===selectedValue)??null; const filterValue=selectedCategory?.value??selectedValue; return { categories, selectedCategory, selectedCategoryValue: filterValue, hasInvalidCategory: Boolean(selectedValue&&!selectedCategory), filteredProducts: filterValue?all.filter(p=>value(p.category)===filterValue):all, featuredProducts: all.filter(p=>p.isFeatured).slice(0,4), bestSellerProducts: all.filter(p=>p.isBestSeller).slice(0,4) };
}
const rows=[{name:'A',category:' Snack   Protein ',isActive:true,isFeatured:true,isBestSeller:true,displayOrder:2},{name:'B',category:'snack protein',isActive:true,isFeatured:false,isBestSeller:false,displayOrder:1},{name:'C',category:'Minuman',isActive:true,isFeatured:false,isBestSeller:true,displayOrder:3},{name:'D',category:'',isActive:true,isFeatured:true,isBestSeller:true,displayOrder:4},{name:'E',category:'Hidden',isActive:false,isFeatured:true,isBestSeller:true,displayOrder:5}];

test('public category derivation normalizes duplicates, removes empty values, and sorts stably',()=>{ assert.deepEqual(cats(rows.filter(p=>p.isActive)),[{value:'minuman',label:'Minuman'},{value:'snack-protein',label:'Snack Protein'}]); });
test('category URLs and query parsing are safe',()=>{ assert.equal(href(null),'/#products'); assert.equal(href('snack-protein'),'/?category=snack-protein#products'); assert.equal(parse(' Snack Protein '),'snack-protein'); assert.equal(parse('x'.repeat(101)),null); assert.equal(parse('bad\nvalue'),null); });
test('catalog filters all products and safely handles missing category matches',()=>{ const all=catalog(rows,null); assert.equal(all.filteredProducts.length,4); const selected=catalog(rows,'snack-protein'); assert.equal(selected.selectedCategory.label,'Snack Protein'); assert.deepEqual(selected.filteredProducts.map(p=>p.name),['B','A']); const invalid=catalog(rows,'zero'); assert.equal(invalid.hasInvalidCategory,true); assert.equal(invalid.filteredProducts.length,0); });
test('featured and best seller sections use manual flags and exclude inactive products while allowing overlap',()=>{ const c=catalog(rows,null); assert.deepEqual(c.featuredProducts.map(p=>p.name),['A','D']); assert.deepEqual(c.bestSellerProducts.map(p=>p.name),['A','C','D']); assert.ok(c.featuredProducts.some(p=>c.bestSellerProducts.includes(p))); });
test('empty sections can be hidden while all products stays visible',()=>{ const c=catalog(rows.map(p=>({...p,isFeatured:false,isBestSeller:false})),null); assert.equal(c.featuredProducts.length,0); assert.equal(c.bestSellerProducts.length,0); assert.equal(c.filteredProducts.length,4); });
test('product mutation allowlist accepts best seller and drops arbitrary fields',()=>{ const input={name:'A',isBestSeller:true,isFeatured:false,id:'bad',createdAt:'bad'}; const db={name:input.name,is_featured:input.isFeatured,is_best_seller:input.isBestSeller}; assert.deepEqual(Object.keys(db),['name','is_featured','is_best_seller']); });
test('demo mode defaults best seller safely when missing',()=>{ assert.equal(Boolean(({isFeatured:true}).isBestSeller),false); });
test('category navigation selected state uses aria-current page',()=>{ const selected=true; assert.equal(selected ? 'page' : undefined, 'page'); });
test('homepage repository fallback can rebuild a catalog from demo rows',()=>{ assert.equal(catalog(rows,'minuman').filteredProducts[0].name,'C'); });
