import { NextResponse } from 'next/server';
import { findOrder } from '../../../../../lib/orders/repository';
import { verifyOrderAccessToken } from '../../../../../lib/orders/access';
import { getSupabaseServerClient } from '../../../../../lib/supabase/server';
import { getMidtransConfig } from '../../../../../lib/midtrans/config';
import { buildSnapPayload, createPaymentAttempt, getLatestPaymentAttempt, isOrderEligibleForPayment, generateProviderOrderId } from '../../../../../lib/midtrans/orders';
import { createSnapTransaction } from '../../../../../lib/midtrans/client';
import { serverLog } from '../../../../../lib/orders/logger';

const ORDER_RE=/^SOIA-\d{8}-[A-Z0-9]{6}$/;
export async function POST(request: Request) { try { const body=await request.json() as {orderNumber?:string; orderAccessToken?:string}; if(!body.orderNumber || !ORDER_RE.test(body.orderNumber)) return NextResponse.json({success:false,message:'Nomor pesanan tidak valid.'},{status:400}); const cfg=getMidtransConfig(); if(!cfg.isConfigured) return NextResponse.json({success:false,message:'Pembayaran online sedang belum tersedia. Silakan coba kembali nanti.'},{status:503}); const {order}=await findOrder(body.orderNumber); if(!order || !order.id) return NextResponse.json({success:false,message:'Pesanan tidak ditemukan.'},{status:404}); const s=getSupabaseServerClient(); const {data: dbOrder}= s ? await s.from('orders').select('order_access_token_hash').eq('id',order.id).single() : {data:null}; if(dbOrder?.order_access_token_hash && !verifyOrderAccessToken(body.orderAccessToken ?? '', dbOrder.order_access_token_hash)) return NextResponse.json({success:false,message:'Akses pesanan tidak valid.'},{status:403}); if(!isOrderEligibleForPayment(order)) return NextResponse.json({success:false,message:'Pesanan tidak dapat dibayar.'},{status:409}); const latest=await getLatestPaymentAttempt(order.id); if(latest?.snap_token && latest?.redirect_url && ['pending',null].includes(latest.transaction_status ?? null) && order.paymentStatus !== 'expired') return NextResponse.json({success:true,token:latest.snap_token,redirectUrl:latest.redirect_url,orderNumber:order.orderNumber}); const providerOrderId=generateProviderOrderId(order.orderNumber,(order.paymentAttemptCount??0)+1); const snap=await createSnapTransaction(buildSnapPayload(order,providerOrderId)); await createPaymentAttempt(order,snap.token,snap.redirect_url); serverLog('info','payment.snap.created',{orderNumber:order.orderNumber,providerOrderId}); return NextResponse.json({success:true,token:snap.token,redirectUrl:snap.redirect_url,orderNumber:order.orderNumber}); } catch(e) { serverLog('error','payment.create.failed',{message:e instanceof Error?e.message:'Unknown'}); return NextResponse.json({success:false,message:'Pembayaran belum dapat dibuka.'},{status:500}); } }
