'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { formatRupiah } from '../../lib/format';
import { readCustomerOrderHistory, type CustomerOrderHistoryItem } from '../../lib/orders/history';
import { ORDER_STATUS_LABELS } from '../../lib/admin/status';
import { PAYMENT_STATUS_LABELS } from '../../lib/midtrans/status';
function d(v:string){return new Intl.DateTimeFormat('id-ID',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v));}
export default function OrdersPage(){ const [orders,setOrders]=useState<CustomerOrderHistoryItem[]|null>(null); useEffect(()=>setOrders(readCustomerOrderHistory()),[]); return <main className="safe mx-auto min-h-screen max-w-2xl px-4 pb-24 text-soia-green"><section className="mt-6 rounded-[2rem] bg-white p-6 shadow-card"><p className="text-xs font-black uppercase tracking-[0.16em] text-soia-green/45">Order Tracking</p><h1 className="mt-2 text-4xl font-black tracking-[-0.05em]">Pesanan Saya</h1><p className="mt-2 text-sm text-soia-green/60">Lihat pesanan yang pernah dibuat dari perangkat ini.</p>{orders===null?<div className="mt-6 space-y-3" aria-busy="true"><div className="h-24 animate-pulse rounded-3xl bg-soia-cream"/><div className="h-24 animate-pulse rounded-3xl bg-soia-cream"/></div>:orders.length?<div className="mt-6 space-y-3">{orders.map(o=><article key={o.orderNumber} className="rounded-3xl border border-soia-green/10 bg-soia-cream/60 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="break-all text-lg font-black">{o.orderNumber}</h2><p className="text-sm text-soia-green/60">{d(o.createdAt)}</p></div>{typeof o.grandTotal==='number'?<strong>{formatRupiah(o.grandTotal)}</strong>:null}</div><div className="mt-3 flex flex-wrap gap-2 text-xs font-bold"><span className="rounded-full bg-white px-3 py-2">{o.orderStatus?ORDER_STATUS_LABELS[o.orderStatus]:'Status belum dimuat'}</span><span className="rounded-full bg-white px-3 py-2">{o.paymentStatus?PAYMENT_STATUS_LABELS[o.paymentStatus]:'Pembayaran belum dimuat'}</span></div><Link className="mt-4 inline-flex min-h-11 items-center rounded-full bg-soia-green px-5 font-bold text-white" href={`/orders/${o.orderNumber}`}>Lihat Pesanan</Link></article>)}</div>:<div className="mt-8 rounded-3xl bg-soia-cream p-6 text-center"><p className="font-bold">Belum ada pesanan yang tersimpan di perangkat ini.</p><Link className="mt-4 inline-flex min-h-11 items-center rounded-full bg-soia-green px-5 font-bold text-white" href="/">Mulai Belanja</Link></div>}</section></main> }
